//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientsWebApp.Blazor.AppLocalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientsWebApp.Blazor.AppLocalization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete? Data will be lost..
        /// </summary>
        public static string AccountDeleteText {
            get {
                return ResourceManager.GetString("AccountDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string AgreeButtonValue {
            get {
                return ResourceManager.GetString("AgreeButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment aren`t approved yet.
        /// </summary>
        public static string AppointmentNotApprovedText {
            get {
                return ResourceManager.GetString("AppointmentNotApprovedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        public static string AppointmentsTab {
            get {
                return ResourceManager.GetString("AppointmentsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string ApproveAppointmentButtonValue {
            get {
                return ResourceManager.GetString("ApproveAppointmentButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status was approved.
        /// </summary>
        public static string ApprovedStatus {
            get {
                return ResourceManager.GetString("ApprovedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to values.
        /// </summary>
        public static string BackToValuesButtonValue {
            get {
                return ResourceManager.GetString("BackToValuesButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string BirthDay {
            get {
                return ResourceManager.GetString("BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelAppointmentButtonValue {
            get {
                return ResourceManager.GetString("CancelAppointmentButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonValue {
            get {
                return ResourceManager.GetString("CancelButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career start year.
        /// </summary>
        public static string CareerStartYear {
            get {
                return ResourceManager.GetString("CareerStartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaints.
        /// </summary>
        public static string Complaints {
            get {
                return ResourceManager.GetString("Complaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conclusions.
        /// </summary>
        public static string Conclusions {
            get {
                return ResourceManager.GetString("Conclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create appointment.
        /// </summary>
        public static string CreateAppointmentButtonValue {
            get {
                return ResourceManager.GetString("CreateAppointmentButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create appointment.
        /// </summary>
        public static string CreateAppointmentTab {
            get {
                return ResourceManager.GetString("CreateAppointmentTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create doctor.
        /// </summary>
        public static string CreateDoctorValue {
            get {
                return ResourceManager.GetString("CreateDoctorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Patient.
        /// </summary>
        public static string CreatePatientButtonValue {
            get {
                return ResourceManager.GetString("CreatePatientButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create result.
        /// </summary>
        public static string CreateResultButtonValue {
            get {
                return ResourceManager.GetString("CreateResultButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create service.
        /// </summary>
        public static string CreateServiceButtonValue {
            get {
                return ResourceManager.GetString("CreateServiceButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create specialization.
        /// </summary>
        public static string CreateSpecializationButtonValue {
            get {
                return ResourceManager.GetString("CreateSpecializationButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        public static string CultureMessage {
            get {
                return ResourceManager.GetString("CultureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to cancel? Changes will not be saved..
        /// </summary>
        public static string DataWillNotChangesText {
            get {
                return ResourceManager.GetString("DataWillNotChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButtonValue {
            get {
                return ResourceManager.GetString("DeleteButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DisagreeButtonValue {
            get {
                return ResourceManager.GetString("DisagreeButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors was not found.
        /// </summary>
        public static string DoctorsNotFoundText {
            get {
                return ResourceManager.GetString("DoctorsNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        public static string DoctorsTab {
            get {
                return ResourceManager.GetString("DoctorsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButtonValue {
            get {
                return ResourceManager.GetString("EditButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit date.
        /// </summary>
        public static string EditDateButtonValue {
            get {
                return ResourceManager.GetString("EditDateButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit office.
        /// </summary>
        public static string EditOfficeTitle {
            get {
                return ResourceManager.GetString("EditOfficeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit result.
        /// </summary>
        public static string EditResultButtonValue {
            get {
                return ResourceManager.GetString("EditResultButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit role.
        /// </summary>
        public static string EditRoleText {
            get {
                return ResourceManager.GetString("EditRoleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit service.
        /// </summary>
        public static string EditServiceButtonValue {
            get {
                return ResourceManager.GetString("EditServiceButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit specialization.
        /// </summary>
        public static string EditSpecializationButtonValue {
            get {
                return ResourceManager.GetString("EditSpecializationButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit status.
        /// </summary>
        public static string EditStatusButtonValue {
            get {
                return ResourceManager.GetString("EditStatusButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to helooooo.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeTab {
            get {
                return ResourceManager.GetString("HomeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House number.
        /// </summary>
        public static string HouseNumber {
            get {
                return ResourceManager.GetString("HouseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make appointment.
        /// </summary>
        public static string MakeAppointmentWithDoctorText {
            get {
                return ResourceManager.GetString("MakeAppointmentWithDoctorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiddleName.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page -&gt;.
        /// </summary>
        public static string NextPageButtonValue {
            get {
                return ResourceManager.GetString("NextPageButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status not approved yey.
        /// </summary>
        public static string NotApprovedStatus {
            get {
                return ResourceManager.GetString("NotApprovedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office was not found.
        /// </summary>
        public static string OfficeNotFound {
            get {
                return ResourceManager.GetString("OfficeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office number.
        /// </summary>
        public static string OfficeNumber {
            get {
                return ResourceManager.GetString("OfficeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offices.
        /// </summary>
        public static string OfficesTab {
            get {
                return ResourceManager.GetString("OfficesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string PatientsTab {
            get {
                return ResourceManager.GetString("PatientsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;-Previous page.
        /// </summary>
        public static string PrevPageButtonValue {
            get {
                return ResourceManager.GetString("PrevPageButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided services.
        /// </summary>
        public static string ProvidedServicesText {
            get {
                return ResourceManager.GetString("ProvidedServicesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receptionists.
        /// </summary>
        public static string ReceptionistsTab {
            get {
                return ResourceManager.GetString("ReceptionistsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recomendations.
        /// </summary>
        public static string Recomendations {
            get {
                return ResourceManager.GetString("Recomendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat your password.
        /// </summary>
        public static string RePassword {
            get {
                return ResourceManager.GetString("RePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SaveChangesButtonValue {
            get {
                return ResourceManager.GetString("SaveChangesButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchButtonValue {
            get {
                return ResourceManager.GetString("SearchButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select date and time.
        /// </summary>
        public static string SelectTimeSlotButtonValue {
            get {
                return ResourceManager.GetString("SelectTimeSlotButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services was not found.
        /// </summary>
        public static string ServicesNotFoundText {
            get {
                return ResourceManager.GetString("ServicesNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string ServicesTab {
            get {
                return ResourceManager.GetString("ServicesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOutTitle {
            get {
                return ResourceManager.GetString("SignOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization.
        /// </summary>
        public static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specializations.
        /// </summary>
        public static string SpecializationsTab {
            get {
                return ResourceManager.GetString("SpecializationsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is active.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
    }
}
